sudo: false

language: rust

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx
  - windows

before_script:
  - rustup component add rustfmt

script:
  - cargo fmt -- --check
  - cargo test
