[package]
name = "pickledb_lists_example"
version = "0.1.0"
authors = ["seladb <pcapplusplus@gmail.com>"]
edition = "2018"

[dependencies]
pickledb = { path = "../../", default-features = false, features = ["bincode"] }
serde = { version = "1.0.82", features = ["derive"] }
