name: Rust test

on: [push, pull_request]

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, nightly, beta]
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: cargo build --examples --lib --bins
      - name: Test
        run: cargo test --verbose --examples --lib --bins

  clippy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- --deny clippy::all

  fmt:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run rustfmt
        run: cargo fmt -- --check
